### ISSUE TITLE
The pretrained model cannot be loaded.

### ISSUE THREAD

**Issue by fjiang9** [gemengtju/SpEx_Plus#4]
Thanks for sharing the code!
Did you try to load the saved model? It seems cannot be loaded successfully.

**Comment by gemengtju** [comment]
Hello Fei Jiang,

 

Maybe you need to modify the path of pretrained model in ‘nnet/separate.py’.Thx.

 

Ge Meng

 

发件人: <noreply@github.com> 代表 Fei Jiang <notifications@github.com>
答复: gemengtju/SpEx_Plus <reply@reply.github.com>
日期: 2020年11月25日 星期三 上午5:47
收件人: gemengtju/SpEx_Plus <SpEx_Plus@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [gemengtju/SpEx_Plus] The pretrained model cannot be loaded. (#4)

 

Thanks for sharing the code!
Did you try to load the saved model? It seems cannot be loaded successfully.

**Comment by fjiang9** [comment]
Hi Ge Meng,

Thanks for the response.

I've downloaded the "best.pt.tar" file from Baidu Cloud. But when I load it using the following code:
checkpoint = torch.load('/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/best.pt.tar', map_location="cpu")

It comes the following error:

Traceback (most recent call last):
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'ZZZZZZZZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 595, in _load
    return legacy_load(f)
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1589, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1619, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 2309, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/test_spex.py", line 3, in <module>
    checkpoint = torch.load('/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/best.pt.tar', map_location="cpu")
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 599, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/best.pt.tar is a zip archive (did you mean to use torch.jit.load()?)
[Finished in 2.1s with exit code 1]
[cmd: ['/Users/jiangfei/opt/anaconda3/envs/py36/bin/python', '-u', '/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/test_spex.py']]
[dir: /Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net]
[path: /Users/jiangfei/opt/anaconda3/bin:/Users/jiangfei/opt/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin]

**Comment by gemengtju** [comment]
Hi Fei Jiang,

 

I have checked it again by following steps, it works well.

 

Best regards,

Ge Meng

 

发件人: <noreply@github.com> 代表 Fei Jiang <notifications@github.com>
答复: gemengtju/SpEx_Plus <reply@reply.github.com>
日期: 2020年11月25日 星期三 下午12:26
收件人: gemengtju/SpEx_Plus <SpEx_Plus@noreply.github.com>
抄送: Meng Ge <gemeng@tju.edu.cn>, Comment <comment@noreply.github.com>
主题: Re: [gemengtju/SpEx_Plus] The pretrained model cannot be loaded. (#4)

 

Hi Ge Meng,

Thanks for the response.

I've downloaded the "best.pt.tar" file from Baidu Cloud. But when I load it using the following code:
checkpoint = torch.load('/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/best.pt.tar', map_location="cpu")

It comes the following error:

Traceback (most recent call last):
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 189, in nti
n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: 'ZZZZZZZZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 2297, in next
tarinfo = self.tarinfo.fromtarfile(self)
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1093, in fromtarfile
obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1035, in frombuf
chksum = nti(buf[148:156])
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 191, in nti
raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 595, in _load
return legacy_load(f)
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 506, in legacy_load
with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, 
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1589, in open
return func(name, filemode, fileobj, **kwargs)
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1619, in taropen
return cls(name, mode, fileobj, **kwargs)
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 1482, in init
self.firstmember = self.next()
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/tarfile.py", line 2309, in next
raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/test_spex.py", line 3, in 
checkpoint = torch.load('/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/best.pt.tar', map_location="cpu")
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 426, in load
return _load(f, map_location, pickle_module, **pickle_load_args)
File "/Users/jiangfei/opt/anaconda3/envs/py36/lib/python3.6/site-packages/torch/serialization.py", line 599, in _load
raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: /Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/best.pt.tar is a zip archive (did you mean to use torch.jit.load()?)
[Finished in 2.1s with exit code 1]
[cmd: ['/Users/jiangfei/opt/anaconda3/envs/py36/bin/python', '-u', '/Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net/test_spex.py']]
[dir: /Users/jiangfei/Downloads/exp_1_1/conv_tasnet/conv-net]
[path: /Users/jiangfei/opt/anaconda3/bin:/Users/jiangfei/opt/anaconda3/condabin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin]

**Comment by fjiang9** [comment]
I guess this may due to we are using different pytorch version. Could you please tell me which pytorch version are you using? 
Thanks!

**Comment by gemengtju** [comment]
Hi Fei Jiang,

 

The version of my pytorch is 1.6.0

Thx.

 

Ge Meng

 

发件人: <noreply@github.com> 代表 Fei Jiang <notifications@github.com>
答复: gemengtju/SpEx_Plus <reply@reply.github.com>
日期: 2020年11月25日 星期三 下午2:26
收件人: gemengtju/SpEx_Plus <SpEx_Plus@noreply.github.com>
抄送: Meng Ge <gemeng@tju.edu.cn>, Comment <comment@noreply.github.com>
主题: Re: [gemengtju/SpEx_Plus] The pretrained model cannot be loaded. (#4)

 

I guess this may due to we are using different pytorch version. Could you please tell me which pytorch version are you using?
Thanks!

**Comment by fjiang9** [comment]
Yes, it works when I update the pytorch to 1.6.0. 
Thank you so much!
